Add GetAllSecurityTestResults
coralogix/cx-api-xdr pull request #80
Opened 2023-01-30 17:20 UTC by GMadorell

[sc-15447]

2023-01-30 17:21 UTC, GMadorell commented on com/coralogix/xdr/v1/test/security_test_service.proto
> +    option (audit_log_description).description = "get security test results for a single test identity";
We might even be able to get rid of the `GetSecurityTestResults` as a refactor later on. We can just specify the test identity as part of the filter and get the first result.
But I think it's best to do it in two endpoints for now.

2023-01-30 17:25 UTC, xBATx commented on com/coralogix/xdr/v1/test/security_test_service.proto
> +    option (audit_log_description).description = "get security test results for a single test identity";
Can't we just make the `test_identity` parameter optional in `GetSecurityTestResults` instead of creating a new endpoint?

2023-01-30 17:26 UTC, GMadorell commented on com/coralogix/xdr/v1/test/security_test_service.proto
> +    option (audit_log_description).description = "get security test results for a single test identity";
The response object is shaped to accommodate only a single security test result, though :S.
This one has an extra wrapper so that we can repeat test results, and we can fit more than one in a single response.

2023-01-30 17:28 UTC, xBATx approved these changes
LGTM 🎉

2023-01-30 17:33 UTC, stsatlantis commented on com/coralogix/xdr/v1/test/security_test_service.proto
> +  message IndividualTestResults {
this shouldn't be in plural. I believe `Result` or `TestResult` or `SecurityTestResult` is better name compared to the `Individual*`

2023-01-30 17:34 UTC, stsatlantis requested changes
Request small renaming.

2023-01-30 17:34 UTC, GMadorell commented on com/coralogix/xdr/v1/test/security_test_service.proto
> +  message IndividualTestResults {
Let's go with Result then 👍

2023-01-30 17:40 UTC, stsatlantis approved these changes

2023-02-01 12:03 UTC, StrDragos approved these changes

2023-02-02 09:46 UTC, merged